/**
 * Container chrome page generation: the same-origin document every Tool Container
 * iframe loads. It carries the generated Framework Library import map (the ONLY supply
 * mechanism for `svelte` and declared libraries — Tools never bundle their own copies)
 * and boots the prebuilt container bootstrap script.
 */
export interface ContainerPageInput {
	/** Import map: bare specifier → URL relative to the container page. */
	importMap: Record<string, string>;
	/** URL of the prebuilt bootstrap bundle, relative to the container page. */
	bootstrapUrl: string;
	/** Tool-owned Svelte stylesheet assets, relative to the container page. */
	stylesheetUrls?: readonly string[];
}

export function renderContainerPage(input: ContainerPageInput): string {
	const importMapJson = JSON.stringify({ imports: input.importMap }, null, 2);
	return `<!doctype html>
<!--
  Deshelf Tool Container (same-origin). Generated by scripts/web-catalog — do not edit.
  The import map supplies Forge Framework Libraries; Tools never bundle their own copies.
  Same-origin supply means this document runs in the Host renderer process: a looping
  tool can freeze the page. No failure isolation is promised (Restart lives in Host
  chrome); this is environment supply, not a security boundary.
-->
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Deshelf Tool Container</title>
	<script type="importmap">
${importMapJson}
	</script>
	<style>
		html,
		body {
			margin: 0;
			padding: 0;
			width: 100%;
			height: 100%;
			overflow: hidden;
			background: transparent;
		}
	</style>
</head>
<body>
${(input.stylesheetUrls ?? []).map((url) => `	<link rel="stylesheet" href="${url}" />`).join('\n')}${(input.stylesheetUrls ?? []).length > 0 ? '\n' : ''}	<script type="module" src="${input.bootstrapUrl}"></script>
</body>
</html>
`;
}
