/**
 * `.deshelf/` IDE declarations for Open Projects.
 *
 * After a successful build the Desktop Forge writes project-local, deterministic
 * generated files that only serve IDE tooling — they never enter the Catalog or any
 * Tool bundle:
 *
 *   <project>/.deshelf/schema.json       extracted descriptors (parameters, assets,
 *                                        commands, private callbacks, outputs,
 *                                        inspector tree) for tooling/dx extensions
 *   <project>/.deshelf/parameters.d.ts   typed `DeshelfParameters`/`DeshelfAssets`/
 *                                        `DeshelfCommands` interfaces + a typed
 *                                        `defineVisualTool` helper overload
 *
 * Generation is idempotent: identical descriptors produce byte-identical files, and
 * `.gitignore` gains a `.deshelf/` entry only when it does not already ignore it.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { AssetSlotDescriptor, CatalogEntry, ParameterDescriptor, ToolCommandDescriptor } from 'tool-contract';

export interface DeshelfFileSet {
	files: Record<string, string>;
}

/** Maps a Parameter descriptor to its TypeScript type for the generated declarations. */
export function parameterTypeScriptType(descriptor: ParameterDescriptor): string {
	switch (descriptor.type) {
		case 'number':
			return 'number';
		case 'boolean':
			return 'boolean';
		case 'string':
			return 'string';
		case 'select': {
			const options = descriptor.constraint.type === 'select' ? descriptor.constraint.options : [];
			return options.length > 0 ? options.map((option: string) => JSON.stringify(option)).join(' | ') : 'string';
		}
		default:
			return 'unknown';
	}
}

function sortedKeys<T>(map: Record<string, T>): Array<[string, T]> {
	return Object.keys(map)
		.sort()
		.map((key) => [key, map[key] as T]);
}

function parametersSection(entry: CatalogEntry): string {
	const lines: string[] = [];
	for (const [id, descriptor] of sortedKeys(entry.parameters)) {
		const mode = descriptor.mode === 'computed' ? ' & { readonly mode: "computed" }' : '';
		lines.push(`\t/** ${descriptor.label} (${descriptor.type}, ${descriptor.mode}). */`);
		lines.push(`\t${JSON.stringify(id)}: ${parameterTypeScriptType(descriptor)}${mode};`);
	}
	return lines.join('\n');
}

function assetsSection(entry: CatalogEntry): string {
	const lines: string[] = [];
	for (const [id, descriptor] of sortedKeys(entry.assets)) {
		const d = descriptor as AssetSlotDescriptor;
		lines.push(`\t/** ${d.kind} asset slot. */`);
		lines.push(`\t${JSON.stringify(id)}: DeshelfAssetContent;`);
	}
	return lines.join('\n');
}

function commandsSection(entry: CatalogEntry): string {
	const lines: string[] = [];
	for (const [id, descriptor] of sortedKeys(entry.commands)) {
		const d = descriptor as ToolCommandDescriptor;
		lines.push(`\t/** ${d.label ?? id}. */`);
		lines.push(`\t${JSON.stringify(id)}: () => void;`);
	}
	return lines.join('\n');
}

const PARAMETERS_DTS_HEADER = `/* Generated by Deshelf Forge for Desktop — do not edit. Regenerated on every successful build. */

export interface DeshelfAssetContent {
	kind: 'blob-url' | 'opaque' | 'empty';
	mime?: string;
	url?: string;
	handle?: string;
}
`;

export function generateDeshelfFiles(entry: CatalogEntry): DeshelfFileSet {
	const schema = {
		generatedBy: 'deshelf-forge-desktop',
		catalogEntryId: entry.catalogEntryId,
		projectId: entry.projectId,
		slug: entry.slug,
		name: entry.name,
		version: entry.version,
		forgeProfile: entry.forgeProfile,
		libraries: entry.libraries,
		parameters: entry.parameters,
		assets: entry.assets,
		commands: entry.commands,
		privateCallbacks: entry.privateCallbacks,
		outputs: entry.outputs,
		inspectorTree: entry.inspectorTree,
		surfaces: entry.surfaces
	};

	const parameterIds = sortedKeys(entry.parameters)
		.map(([id]) => `\t${JSON.stringify(id)}: ParameterValue;`)
		.join('\n');
	const parameters = parametersSection(entry);
	const assets = assetsSection(entry);
	const commands = commandsSection(entry);
	const hasAssets = Object.keys(entry.assets).length > 0;
	const hasCommands = Object.keys(entry.commands).length > 0;
	const parametersDts = `${PARAMETERS_DTS_HEADER}
export type ParameterValue = number | boolean | string;

export interface DeshelfParameters {
${parameters.length > 0 ? `${parameters}\n` : '\t// no parameters declared\n'}
}

${hasAssets ? `export interface DeshelfAssets {\n${assets}\n}\n\n` : ''}export type DeshelfParameterSnapshot = {
${parameterIds.length > 0 ? `${parameterIds}\n` : '\t// no parameters declared\n'}
};

declare module '@deshelf/tool-sdk' {
	interface DeshelfToolTypes {
		parameters: DeshelfParameters;
		${hasAssets ? 'assets: DeshelfAssets;' : ''}
		${hasCommands ? `commands: {\n${commands}\n\t};` : ''}
	}
}
`;

	const files: Record<string, string> = {
		'schema.json': `${JSON.stringify(schema, null, 2)}\n`,
		'parameters.d.ts': parametersDts
	};
	return { files };
}

/**
 * Writes the `.deshelf/` file set idempotently (byte-identical outputs are left
 * untouched so editors/watchers never churn) and maintains the project `.gitignore`.
 */
export async function writeDeshelfDeclarations(
	projectDir: string,
	entry: CatalogEntry,
	typeofFs: typeof fs = fs
): Promise<{ written: string[]; unchanged: string[] }> {
	const { files } = generateDeshelfFiles(entry);
	const targetDir = path.join(projectDir, '.deshelf');
	await typeofFs.mkdir(targetDir, { recursive: true });

	const written: string[] = [];
	const unchanged: string[] = [];
	for (const name of Object.keys(files).sort()) {
		const target = path.join(targetDir, name);
		const content = files[name] as string;
		let existing: string | undefined;
		try {
			existing = await typeofFs.readFile(target, 'utf8');
		} catch {
			existing = undefined;
		}
		if (existing === content) {
			unchanged.push(name);
			continue;
		}
		await typeofFs.writeFile(target, content, 'utf8');
		written.push(name);
	}

	await ensureDeshelfIgnored(projectDir, typeofFs);
	return { written, unchanged };
}

/** Idempotent: appends `.deshelf/` to .gitignore only when not already ignored. */
export async function ensureDeshelfIgnored(projectDir: string, typeofFs: typeof fs = fs): Promise<boolean> {
	const gitignorePath = path.join(projectDir, '.gitignore');
	let content = '';
	try {
		content = await typeofFs.readFile(gitignorePath, 'utf8');
	} catch {
		content = '';
	}
	const alreadyIgnored = content
		.split(/\r?\n/)
		.map((line) => line.trim())
		.some((line) => line === '.deshelf/' || line === '.deshelf' || line === '/.deshelf/');
	if (alreadyIgnored) return false;
	const prefix = content.length === 0 ? '' : content.endsWith('\n') ? '' : '\n';
	await typeofFs.writeFile(gitignorePath, `${prefix}${content.length > 0 ? '' : ''}.deshelf/\n`, 'utf8');
	return true;
}
